### ISSUE TITLE
[Bug] Map preview is not visible

### ISSUE THREAD

**Issue by salvatoreboemia** [ngocjohn/vehicle-info-card#100]
### Short summary 📝

Map preview is not visible

### Detailed description 📋

Hi

do you know why the map preview is not visible?

<img width="478" alt="Screenshot 2024-12-23 at 00 19 26" src="https://github.com/user-attachments/assets/e8e7abae-8c23-4002-ab2e-2ba6a8708df6" />

thanks

### Version 📦

v1.6.0

**Comment by ngocjohn** [comment]
Hi @salvatoreboemia, today I released a [beta version ](https://github.com/ngocjohn/vehicle-info-card/releases/tag/v1.6.1-beta.2)which includes a bug fix. I didn't expect so much interest in using the card, so because of that the limit for api request map rendering was exceeded.  I changed the provider for the map without registration, via another service. The new one is, in my opinion, contains a bit too much data for the map and is not really suitable for customization with themes. But the purpose for device tracking is fulfilled.. I will test the feature and soon I will release the official release.
