### ISSUE TITLE
Translation of card to languages other than English[Feature] 

### ISSUE THREAD

**Issue by piotrgt** [ngocjohn/vehicle-info-card#21]
### Short summary

Add translation possibility

### Detailed description

First of all, thanks for preparing this card, it's been a great addition to the MercedeMe component!
Would it be possible to open translation to other languages, so that the card and the functions are displayed in the same language as rest of my dashboard?

**Comment by ngocjohn** [comment]
Hi, it was mentioned in the forum that in the future there will be a translation for entities... Now the names are taken from the original name by component, if translations for other languages will be available, I will add this feature to the card... But I will try to think of another way to add invidual translation for entity names.

**Comment by piotrgt** [comment]
Ok, so if I understood you correctly when the entities in Mercedes ME component will be translated to local language (Polish in my case) the addon would display them translated?
Or alternatively using the method you just discovered translations could be maintained directly in the addon?

**Comment by ngocjohn** [comment]
In Home Assistant, there is an attribute called 'translation key' for entities that handles translations. This attribute displays the entity's name or state based on the language setting, provided the developer has included translation files for the component.

For our vehicles, ReneNulschDE's component uses these translation keys as internal names and also includes original name attributes that are displayed as the entity's name. To support this, I created translation files for the card, containing these keys and their respective translations.

I have now finished the translation for each sub card with English translation, only the translation for 'services' is missing. According to the eng file, I can then create a template for the other languages, which I will provide via Weblate and the other user can contribute his translation for the other languages. It was easier for me, because I have these keys ready since the beginning of the card development. For demonstration I send a preview for Czech lang 😅

![CleanShot 2024-07-31 at 00 29 31@2x](https://github.com/user-attachments/assets/aef7693a-4147-4fe1-ad04-c1406cef58ae)

**Comment by ngocjohn** [comment]
@piotrgt Added translations in beta v1.1.0-alpha.. 😄 Can you try it and please give me feedback?

**Comment by piotrgt** [comment]
I installed updated version of the card and everything worked out of the box. After changing the language most of the descriptions, services and statuses were visible in Polish. Please see below screenshots.
Only strings that seem to be not included in translation are: 
- vehicle status on the main screen, which is either "locked" or "unlocked"
- ignition state in the vehicle status tab
- 
![vehicle_card](https://github.com/user-attachments/assets/289db36b-8a87-4996-9dc3-eebef1546ec3)

(On a side note I noticed that card name is not afected by card_mod font styling)

**Comment by ngocjohn** [comment]
Yes I know, because for the sensor in the button I left the original state from HA, if you change the language directly in the system to PL, it will be in PL 😄  But probably in the final version, I will add also these states to translate into the chosen language.  Please check the file with PL translation.  Probably there will be some wrong translations, because I had it generated via translator, as well as for the other languages. Therefore I will be very glad for any PR that will help to improve the card more... 

for header title use this, I set the font similarly from the app.. but you can change anything with this. 

```yaml
card_mod:
  style: |
    ha-card header h1 {
      font-family: arial !important;
    }
```

**Comment by mrspouse** [comment]
Great card! Can I just add a related request for translations of sensor names into local English, for example GBR terms:
Gas lock = Fuel filler flap lock
Deck lid = Luggage compartment

(Also, engineHoodStatus - aka Bonnet - is missing)

**Comment by ngocjohn** [comment]
Hi @mrspouse , can you please edit the src/localize/string.json file, which is the base and create PR with new names?  Thanks 😄
