### ISSUE TITLE
[Feature] Display Battery Level and Electric Range

### ISSUE THREAD

**Issue by DoctorExitus** [ngocjohn/vehicle-info-card#43]
### Short summary

Display Battery Level and Electric Range analogous to Fuel Level and Liquid Range

### Detailed description

For PHEVs and EVs, the electric range and state of charge are important pieces of information that should be visible at a glance. Currently, these details are buried under trip data. It would be useful to have a toggle that enables a bar similar to the green one for fuel level and liquid range. The electric bar should be displayed above the fuel bar, as it usually depletes first. To make it easily distinguishable, the bar should be a different color, such as blue.

**Comment by ngocjohn** [comment]
Hi @DoctorExitus, if I understand correctly. So you have both fuel level.fuel range sensors and range sensors for electric cars? Can you please explain which sensors you have in mind? Because now on the main card the status of Fuel level and Range Liquid is displayed and vice versa in case of EV so Range electric and SoC .. I mean if you have all these entities then both progress bars should be displayed. 🤔  Can you please post a screen of the sensors you have in mind? If possible, I will definitely add a function to switch between these data 😄 👍

**Comment by Mozartuss** [comment]
I have a hybrid Mercedes E 300 de T-Modell Hybrid car, and the Card works nearly perfect. But I can't see the second electric state, I can only see the current fuel state and the range.
Did I have to change something in the default YAML config?

**Comment by ngocjohn** [comment]
Hi @Mozartuss, no, the added view is not yet in the latest release. It will be in the new one, which is still in need of a little tweaking and is yet to be released.

**Comment by DoctorExitus** [comment]
Looks amazing, can't wait for the release. Thanks for implementing this so quickly.

**Comment by ngocjohn** [comment]
@DoctorExitus You can try the pre-release version, I added some other changes. 😄 
https://github.com/ngocjohn/vehicle-info-card/releases/tag/v1.2.0-beta_2
